service: webscraper-aws


provider:
  name: aws
  region: sa-east-1
  runtime: nodejs14.x

plugins:
  - serverless-mocha-plugin
  - serverless-offline    

Layers:
  - 'arn:aws:lambda:sa-east-1:764866452798:layer:chrome-aws-lambda:25'

functions:
  webscrap:
    handler: handler/webscrap/controller.handler
    events:
      - http:
          path: /webscrap
          method: get
  products:
    handler: handler/products/controller.handler
    events:
      - http:
          path: /products
          method: get